### ISSUE TITLE
unable to migrate with mysql db (xampp)

### ISSUE THREAD

**Issue by shmanoj16** [evereux/flicket#22]
Hi @evereux  I have my mysql db created with xampp server.

> url : localhost
> port:80
> when run this uri it redirects to localhost/phpmyadmin

I created a new database called flicket without any table.

Ran config_json.py and provided the below details.
`[{"db_username": "root", "db_password": "", "db_url": "localhost", "db_port": "80", "db_name": "flicket", "SECRET_KEY": "l5y5MX+m3jNGIg52+9o0YbVUKGUrZ+Mo", "NOTIFICATION_USER_PASSWORD": "NMZjRGnC19H5n/IcylpP5GvveQIaj7G/"}](url)`

when I run , python manage.py db init

```
(ticketsys) D:\Practice\flicket>python manage.py db init
Creating directory D:\Practice\flicket\migrations ... done
Creating directory D:\Practice\flicket\migrations\versions ... done
Generating D:\Practice\flicket\migrations\alembic.ini ... done
Generating D:\Practice\flicket\migrations\env.py ... done
Generating D:\Practice\flicket\migrations\README ... done
Generating D:\Practice\flicket\migrations\script.py.mako ... done
Please edit configuration/connection/logging settings in 'D:\\Practice\\flicket\\migrations\\alembic.ini' before proceeding.
```

when I run python manage.py db migrate 

```
(ticketsys) D:\Practice\flicket>python manage.py db migrate
Traceback (most recent call last):
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\sqlalchemy\engine\base.py", line 2262, in _wrap_pool_connect
    return fn()
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\sqlalchemy\pool\base.py", line 294, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\sqlalchemy\pool\base.py", line 751, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\sqlalchemy\pool\base.py", line 483, in checkout
    rec = pool._do_get()
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\sqlalchemy\pool\impl.py", line 237, in _do_get
    return self._create_connection()
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\sqlalchemy\pool\base.py", line 299, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\sqlalchemy\pool\base.py", line 428, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\sqlalchemy\pool\base.py", line 630, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\sqlalchemy\engine\default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\pymysql\connections.py", line 597, in connect
    self._get_server_information()
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\pymysql\connections.py", line 966, in _get_server_information
    packet = self._read_packet()
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\pymysql\connections.py", line 656, in _read_packet
    packet_header = self._read_bytes(4)
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\pymysql\connections.py", line 702, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 25, in <module>
    manager.run()
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\flask_script\__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\flask_script\__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\flask_script\commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\flask_migrate\__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\flask_migrate\__init__.py", line 215, in migrate
    version_path=version_path, rev_id=rev_id)
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\alembic\command.py", line 176, in revision
    script_directory.run_env()
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\alembic\script\base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\alembic\util\pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\alembic\util\compat.py", line 82, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations\env.py", line 87, in <module>
    run_migrations_online()
  File "migrations\env.py", line 72, in run_migrations_online
    connection = engine.connect()
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\sqlalchemy\engine\base.py", line 2193, in connect
    return self._connection_cls(self, **kwargs)
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\sqlalchemy\engine\base.py", line 103, in __init__
    else engine.raw_connection()
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\sqlalchemy\engine\base.py", line 2293, in raw_connection
    self.pool.unique_connection, _connection
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\sqlalchemy\engine\base.py", line 2266, in _wrap_pool_connect
    e, dialect, self
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\sqlalchemy\engine\base.py", line 1536, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\sqlalchemy\util\compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\sqlalchemy\util\compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\sqlalchemy\engine\base.py", line 2262, in _wrap_pool_connect
    return fn()
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\sqlalchemy\pool\base.py", line 294, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\sqlalchemy\pool\base.py", line 751, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\sqlalchemy\pool\base.py", line 483, in checkout
    rec = pool._do_get()
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\sqlalchemy\pool\impl.py", line 237, in _do_get
    return self._create_connection()
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\sqlalchemy\pool\base.py", line 299, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\sqlalchemy\pool\base.py", line 428, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\sqlalchemy\pool\base.py", line 630, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\sqlalchemy\engine\default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\pymysql\connections.py", line 597, in connect
    self._get_server_information()
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\pymysql\connections.py", line 966, in _get_server_information
    packet = self._read_packet()
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\pymysql\connections.py", line 656, in _read_packet
    packet_header = self._read_bytes(4)
  File "C:\Users\manoj.sh\.conda\envs\ticketsys\lib\site-packages\pymysql\connections.py", line 702, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
(Background on this error at: http://sqlalche.me/e/e3q8)

```

**Please help me to resolve this problem, do we need to create tables manually??**

**Comment by evereux** [comment]
> url : localhost
> port:80
> when run this uri it redirects to localhost/phpmyadmin

Sorry, I don't know what this has to do with Flicket?

The problem here is with your config.json I think. You don't normally connect to the database on port 80 (that's normally your webserver). If it's mysql that would typically be port 3306. Do you use mysql workbench? Try setting that up if not. The details you enter there to connect to mysql can be the same details you use for the db connections which you define in the config.json. Also, don't use root to connect to the database. Create a mysql user to access the flicket database only.

No, you do not need to create the tables manually.

**Comment by evereux** [comment]
Did you manage to resolve this error? Did you read the link in the error message suggests? : [http://sqlalche.me/e/e3q8](http://sqlalche.me/e/e3q8)

Also, you could create a local script to test your database credentials. See [https://docs.sqlalchemy.org/en/13/core/engines.html](https://docs.sqlalchemy.org/en/13/core/engines.html) for examples. I'll try and get round to setting something up that tests the connection and reports errors more succinctly.

Finally, this is the typical formatting of a config.json file (the formatting shown above is wrong):

    {"db_username": "<database_username_root_is_bad>", "db_password": "<your_db_user_password>", "db_url": "localhost", "db_port": "<3306_is_typically_used_by_mysql>", "db_name": "<database_name>", "SECRET_KEY": "<automatically_generated>", "NOTIFICATION_USER_PASSWORD": "<automatically_generated>"}

**Comment by evereux** [comment]
Closing this ticket as I believe this is a configuration setting issue and I've received no feedback.

If this is still deemed to be a problem with Flicket please feel free to open another ticket and I'll help if I can.
