### ISSUE TITLE
Error while using migrate

### ISSUE THREAD

**Issue by coutoreis** [evereux/flicket#35]
Following the installation steps, when I run `python manage.py db migrate ` I receive the following error:
```
python manage.py db migrate                                                                                                                                   
Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    manager.run()
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/flask_migrate/__init__.py", line 215, in migrate
    version_path=version_path, rev_id=rev_id)
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/alembic/command.py", line 176, in revision
    script_directory.run_env()
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/alembic/util/compat.py", line 82, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 87, in <module>
    run_migrations_online()
  File "migrations/env.py", line 70, in run_migrations_online
    poolclass=pool.NullPool)
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/__init__.py", line 498, in engine_from_config
    return create_engine(url, **options)
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/__init__.py", line 455, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 54, in create
    u = url.make_url(name_or_url)
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 229, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 288, in _parse_rfc1738_args
    return URL(name, **components)
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 71, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: ''
```

What am I missing?

**Comment by coutoreis** [comment]
I receive a similiar message running `python manage.py run_set_up`                                                                                                                                   

```
Enter admin email: bla@bla.com
Enter password: 
Re-enter password: 
Please enter site base url including port. For example this would be "http://192.168.1.1:8000".
Base url> http://127.0.0.1:8000              
Traceback (most recent call last):
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7fd3fe7c5cb0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    manager.run()
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/home/tcouto/projects/flicket_0.2.0/setup.py", line 43, in run
    self.set_db_config_defaults()
  File "/home/tcouto/projects/flicket_0.2.0/setup.py", line 60, in set_db_config_defaults
    count = FlicketConfig.query.count()
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 519, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 78, in __call__
    return self.registry()
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 1012, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3206, in __call__
    return self.class_(**local_kw)
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 138, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 937, in engine
    return self.get_engine()
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 956, in get_engine
    return connector.get_engine()
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 559, in get_engine
    sa_url = make_url(uri)
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 229, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 288, in _parse_rfc1738_args
    return URL(name, **components)
  File "/home/tcouto/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 71, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: ''
```

**Comment by evereux** [comment]
Please can you detail all the steps you carried out prior to running `python manage.py db migrate` so I can try and reproduce the issue.

Which database server are you using?

I see you are using anaconda3. What version specifically?

Did you set up a virtual environment? It looks to me you've installed the requirements globally to anaconda? How does your `pip freeze` compare to `requirements.txt` bundle with flicket? Anacondas default package installations maybe causing the problem?

No point going any further if the migrations don't work.

**Comment by xdml** [comment]
From the traceback it looks like you have configured `db_port`, but it is empty string. Can you check what do you have in `config.json` file?

It should look like (in case of MariaDB):

```
{
  "db_username": "flicket",
  "db_password": "secret",
  "db_url": "localhost",
  "db_port": "3306",
  "db_name": "flicket,
  "SECRET_KEY": "random string",
  "NOTIFICATION_USER_PASSWORD": "password"
}
```

If you are installing new instance, have you executed `python -m scripts.create_json` and provided correct port number?

For me it looks like your `db_port` is empty string, so `sqlalchemy` is failing.

**Comment by evereux** [comment]
I just removed the db port number from my config.json file and got a similar failure trying a migration.

**Comment by xdml** [comment]
And does it work without `db_port` - the application itself? Because from the traceback it looks like `sqlalchemy.engine.url.URL` is failing. So I expect, that the application itself is not working. Just my guess.

**Comment by evereux** [comment]
`python manage.py runserver` will run without port. I did not try `python manage.py run_set_up` as that will be the same error as above.

I think the problem definitely lies with the `config.json` file.

It's probably a good idea for me to force a validation check of the config.json file and ensure that the db connection is good before trying to migrate. Easy enough to do I think. 

At the moment the application only checks that the json exists. So, if it doesn't exist and you try to migrate you'll see `Config json file "/home/evereux/python/projects/flicket/config.json" does not exist. Exiting application.`. This is triggered by `config.py`->`WriteConfig.json_exists()`. I can add a `check_db_connection()`.

**Comment by xdml** [comment]
In my case, if I set `db_port` to `''` application itself is not working. Ok `python manage.py runserver` starts, but on page load it will result in same error...

**Comment by xdml** [comment]
And one point, I am not sure, what should be in `db_port` if sqlite is used...

**Comment by evereux** [comment]
> In my case, if I set `db_port` to `''` application itself is not working. Ok `python manage.py runserver` starts, but on page load it will result in same error...

Yes, that's expected.

SQLite does not expect a port so can be left blank for those cases. The path to the SQL file does need to be explicitly set if I remember correctly. I seem to recall a few cases in other flask applications I've played with that the db file can be created in one place and then expected to be in another.

We really need feedback from @coutoreis at this point though.


I've now added a check to 0.2.1 that checks the database connection on start-up and returns the following if it fails:

> ...
  File "/home/evereux/python/projects/flicket/config.py", line 15, in <module>
    class BaseConfiguration(object):
  File "/home/evereux/python/projects/flicket/config.py", line 67, in BaseConfiguration
    check_db_connection(SQLALCHEMY_DATABASE_URI)
  File "/home/evereux/python/projects/flicket/scripts/create_json.py", line 116, in check_db_connection
    raise Exception(base_error_message)
Exception: There was a problem connecting to the database. Please check your config.json file.

**Comment by coutoreis** [comment]
People, sorry. I had personal issues in the later days. I'm back to action.

First of all, I'm trully glad with all the feedbacks in so brief time!

@evereux I'm using `psql`, indeed installed reqs globally on anaconda (didn't create `venv`), all reqs version are correct at `pip freeze`
About `anaconda3`:
```bash
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
```
I
@xdml I'm using Postgres.

So, I'll try MariaDB for now and then return here to paste the feedback. Let's see if it works.

**Comment by evereux** [comment]
Before you change databases can you switch to the 0.2.1 branch and try to 
connect?

Also, double check your config.json file. I suspect that's where the error 
lies and switching to another dB type won't help.

**Comment by coutoreis** [comment]
So, there was an issue with my Postgres connector. Even when I try to connect from terminal I get an authentication error. As I'm on top of schedule, I changed to MySQL and worked perfectly.

Thanks for the help. I'll try to also collaborate here soon.

> Before you change databases can you switch to the 0.2.1 branch and try to connect? Also, double check your config.json file. I suspect that's where the error lies and switching to another dB type won't help.
> […](#)
> On 28 November 2019 00:35:25 Thiago do Couto ***@***.***> wrote: People, sorry. I had personal issues in the later days. I'm back to action. First of all, I'm trully glad with all the feedbacks in so brief time! @evereux I'm using psql, indeed installed reqs globally on anaconda (didn't create venv), all reqs version are correct at pip freeze About anaconda3: conda version : 4.7.12 conda-build version : 3.18.9 python version : 3.7.4.final.0 I @xdml I'm using Postgres. So, I'll try MariaDB for now and then return here to paste the feedback. Let's see if it works. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by evereux** [comment]
Glad you got it working and thanks for the feedback.

>
