### ISSUE TITLE
Missing step in set up docs

### ISSUE THREAD

**Issue by ttabwol** [evereux/flicket#51]
https://flicket.readthedocs.io/en/latest/install.html#set-up

I'm trying to install flicket in a development environment but running step 6 crashes because there are some tables missing in the database. Step 5 is missing so I thought there's something I should do previously to running the set up?

Any help will be appreciated. Thanks in advance!

**Comment by evereux** [comment]
The numbering is just cocked up. 

Step 4 'should' create the tables required.

How is step 6 crashing? Please provide the traceback log.

**Comment by ttabwol** [comment]
Here's the log. I have a MySQL server running locally with a 'flicket' empty database. As far as I can see the script is trying to count from a table that doesn't exist.
---
(venv) C:\Projects\flicket>python -m scripts.create_json


Configuration json file already exists. Do you wish to overwrite? (Y/n) > Y
Enter database username: root
Password must:
  * be a minimum of 8 characters long.
  * contain numbers and letters.
  * contain one lowercase and one uppercase letter.
Enter database password:
Re-enter database password:
Enter database url (don't include port). If running locally this would be localhost: localhost
Enter database port: 3306
Enter database name: flicket
Writing config file to C:\Projects\flicket\config.json

(venv) C:\Projects\flicket>python manage.py db upgrade
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.

(venv) C:\Projects\flicket>python manage.py run_set_up
Enter admin email: xabi.moreno@entercoms.com
Enter password:
Re-enter password:
Please enter site base url including port. For example this would be "http://192.168.1.1:8000".
Base url> http://127.0.0.1:8000
Traceback (most recent call last):
  File "C:\Projects\flicket\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "C:\Projects\flicket\venv\lib\site-packages\sqlalchemy\engine\default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Projects\flicket\venv\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "C:\Projects\flicket\venv\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "C:\Projects\flicket\venv\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Projects\flicket\venv\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "C:\Projects\flicket\venv\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "C:\Projects\flicket\venv\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "C:\Projects\flicket\venv\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Projects\flicket\venv\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'flicket.flicket_config' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 31, in <module>
    manager.run()
  File "C:\Projects\flicket\venv\lib\site-packages\flask_script\__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "C:\Projects\flicket\venv\lib\site-packages\flask_script\__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "C:\Projects\flicket\venv\lib\site-packages\flask_script\commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "C:\Projects\flicket\setup.py", line 43, in run
    self.set_db_config_defaults()
  File "C:\Projects\flicket\setup.py", line 60, in set_db_config_defaults
    count = FlicketConfig.query.count()
  File "C:\Projects\flicket\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3560, in count
    return self.from_self(col).scalar()
  File "C:\Projects\flicket\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3304, in scalar
    ret = self.one()
  File "C:\Projects\flicket\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3274, in one
    ret = self.one_or_none()
  File "C:\Projects\flicket\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3243, in one_or_none
    ret = list(self)
  File "C:\Projects\flicket\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3316, in __iter__
    return self._execute_and_instances(context)
  File "C:\Projects\flicket\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3341, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "C:\Projects\flicket\venv\lib\site-packages\sqlalchemy\engine\base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "C:\Projects\flicket\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Projects\flicket\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "C:\Projects\flicket\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\Projects\flicket\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "C:\Projects\flicket\venv\lib\site-packages\sqlalchemy\util\compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Projects\flicket\venv\lib\site-packages\sqlalchemy\util\compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "C:\Projects\flicket\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "C:\Projects\flicket\venv\lib\site-packages\sqlalchemy\engine\default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Projects\flicket\venv\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "C:\Projects\flicket\venv\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "C:\Projects\flicket\venv\lib\site-packages\pymysql\connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Projects\flicket\venv\lib\site-packages\pymysql\connections.py", line 727, in _read_query_result
    result.read()
  File "C:\Projects\flicket\venv\lib\site-packages\pymysql\connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "C:\Projects\flicket\venv\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "C:\Projects\flicket\venv\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Projects\flicket\venv\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'flicket.flicket_config' doesn't exist")
[SQL: SELECT count(*) AS count_1
FROM (SELECT flicket_config.id AS flicket_config_id, flicket_config.mail_server AS flicket_config_mail_server, flicket_config.mail_port AS flicket_config_mail_port, flicket_config.mail_use_tls AS flicket_config_mail_use_tls, flicket_config.mail_use_ssl AS flicket_conf
ig_mail_use_ssl, flicket_config.mail_debug AS flicket_config_mail_debug, flicket_config.mail_username AS flicket_config_mail_username, flicket_config.mail_password AS flicket_config_mail_password, flicket_config.mail_default_sender AS flicket_config_mail_default_sende
r, flicket_config.mail_max_emails AS flicket_config_mail_max_emails, flicket_config.mail_suppress_send AS flicket_config_mail_suppress_send, flicket_config.mail_ascii_attachments AS flicket_config_mail_ascii_attachments, flicket_config.posts_per_page AS flicket_config
_posts_per_page, flicket_config.allowed_extensions AS flicket_config_allowed_extensions, flicket_config.ticket_upload_folder AS flicket_config_ticket_upload_folder, flicket_config.avatar_upload_folder AS flicket_config_avatar_upload_folder, flicket_config.application_
title AS flicket_config_application_title, flicket_config.base_url AS flicket_config_base_url, flicket_config.auth_domain AS flicket_config_auth_domain, flicket_config.use_auth_domain AS flicket_config_use_auth_domain, flicket_config.csv_dump_limit AS flicket_config_c
sv_dump_limit, flicket_config.change_category AS flicket_config_change_category, flicket_config.change_category_only_admin_or_super_user AS flicket_config_change_category_only_admin_or_super_user
FROM flicket_config) AS anon_1]
(Background on this error at: http://sqlalche.me/e/f405)

**Comment by evereux** [comment]
There's something wrong with your installation at step 4. I've just cloned the github repository and ran through the installation steps just fine.

Your step 4:

    (venv) C:\Projects\flicket>python manage.py db upgrade
    INFO [alembic.runtime.migration] Context impl MySQLImpl.
    INFO [alembic.runtime.migration] Will assume non-transactional DDL.

Mine:

    INFO  [alembic.runtime.migration] Context impl MySQLImpl.
    INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
    INFO  [alembic.runtime.migration] Running upgrade  -> fe0f77ef3f46, migrations before source code control
    INFO  [alembic.runtime.migration] Running upgrade fe0f77ef3f46 -> 36c91aa9b3b5, new action model
    INFO  [alembic.runtime.migration] Running upgrade 36c91aa9b3b5 -> 253ae54f5788, change category config options
    INFO  [alembic.runtime.migration] Running upgrade 253ae54f5788 -> 70820003badd, add logging of hours
    INFO  [alembic.runtime.migration] Running upgrade 70820003badd -> bcac6741b320, hours scale two dp
    INFO  [alembic.runtime.migration] Running upgrade bcac6741b320 -> 9e59e0b9d1cf, last updated
    Updating last_updated dates.
    No database updates required.


I'm guessing you have downloaded the zip file and not cloned from github which could explain the reason. Checking the archive I see that the folder ./migrations is missing which is now a requirement and an utter cock up on my behalf. The folder has been a requirement for a few revisions now and no-one has reported the issue so I guess people are just cloning from github.

If you create that folder and populate it with the files here: https://github.com/evereux/flicket/tree/master/migrations and run step 4 again you should be good.

I'll update the zip ASAP.

Cheers

**Comment by evereux** [comment]
Updated latest zip to include migrations folder: https://github.com/evereux/flicket/blob/master/dist/flicket_0.2.2.zip

**Comment by ttabwol** [comment]
Hi again :)

I've replaced the migrations folder for the one from github and everything is working smoothly now. Thank you very much!

**Comment by evereux** [comment]
Great. Glad you got it resolved and thanks for reporting.

**Comment by evereux** [comment]
Closing ticket as issue is resolved.
