### ISSUE TITLE
Installation time error - sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:mysql.None

### ISSUE THREAD

**Issue by gpnaveen** [evereux/flicket#58]
I am getting below error. Trying to install on Ubuntu 18.04 LTS.

root@frr:/home/snag/flicket# python manage.py db upgrade
Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    from setup import RunSetUP
  File "/home/snag/flicket/setup.py", line 10, in <module>
    from application import db, app
  File "/home/snag/flicket/application/__init__.py", line 40, in <module>
    app.config.from_object('config.BaseConfiguration')
  File "/usr/local/lib/python3.6/dist-packages/flask/config.py", line 174, in from_object
    obj = import_string(obj)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/utils.py", line 871, in import_string
    __import__(import_name)
  File "/home/snag/flicket/config.py", line 16, in <module>
    class BaseConfiguration(object):
  File "/home/snag/flicket/config.py", line 93, in BaseConfiguration
    check_db_connection(SQLALCHEMY_DATABASE_URI)
  File "/home/snag/flicket/scripts/create_json.py", line 131, in check_db_connection
    engine = create_engine(sqlalchemy_database_uri)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/create.py", line 534, in create_engine
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/url.py", line 645, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/langhelpers.py", line 344, in load
    "Can't load plugin: %s:%s" % (self.group, name)
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:mysql.None

**Comment by evereux** [comment]
Did you follow step #3 from the installation documentation?

[setup](https://flicket.readthedocs.io/en/latest/install.html#set-up)

**Comment by evereux** [comment]
Closing due to no further feedback.
