### ISSUE TITLE
bug in requirements.txt

### ISSUE THREAD

**Issue by akbp0** [evereux/flicket#82]
in requirements.txt you are installing Werkzeug==3.0.3
but after install it it will raise error :
`Error: While importing 'application', an ImportError was raised:

Traceback (most recent call last):
  File "/home/apa/Downloads/flicket-master/env/lib/python3.12/site-packages/flask/cli.py", line 219, in locate_app
    __import__(module_name)
  File "/home/apa/Downloads/flicket-master/application/__init__.py", line 23, in <module>
    from flask_login import LoginManager
  File "/home/apa/Downloads/flicket-master/env/lib/python3.12/site-packages/flask_login/__init__.py", line 12, in <module>
    from .login_manager import LoginManager
  File "/home/apa/Downloads/flicket-master/env/lib/python3.12/site-packages/flask_login/login_manager.py", line 33, in <module>
    from .utils import _create_identifier
  File "/home/apa/Downloads/flicket-master/env/lib/python3.12/site-packages/flask_login/utils.py", line 14, in <module>
    from werkzeug.urls import url_decode
ImportError: cannot import name 'url_decode' from 'werkzeug.urls' (/home/apa/Downloads/flicket-master/env/lib/python3.12/site-packages/werkzeug/urls.py)

Usage: flask [OPTIONS] COMMAND [ARGS]...
Try 'flask --help' for help.

Error: No such command 'db'.
`
by install Werkzeug==2.3.7   problem will solve

**Comment by alwin4711** [comment]
Same result.
